# https://docs.github.com/en/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 50
    ignore:
      # Has breaking changes that require careful rollout. https://socket.io/blog/engine-io-4-release/#Major-breaking-changes
      - dependency-name: "engine.io"
        versions: ["4.x"]
    reviewers:
      - "coda-hq/sre"
