name: CI

on:
  push:
  pull_request:
  schedule:
    - cron: '0 0 * * 0'

jobs:
  test-node:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x, 15.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npm test
        env:
          CI: true

  build-examples:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        example:
          - angular-todomvc
          - create-react-app-example
          - custom-parsers
          - private-messaging
          - typescript
          - webpack-build
          - webpack-build-server

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Use Node.js 20
        uses: actions/setup-node@v3
        with:
          node-version: 20
          
      - name: Build ${{ matrix.example }}
        run: |
          cd examples/${{ matrix.example }}
          npm install
          npm run build
